### ISSUE TITLE
Some typos in NC `server` OpenAPI generated files

### ISSUE THREAD

**Issue by bigcat88** [provokateurin/ocs_api_viewer#5]
https://github.com/nextcloud/server/blob/bef40531f0820b8ba1869524b3a9830a10413b1b/apps/files_sharing/openapi.json#L1326
should be "-1"

https://github.com/nextcloud/server/blob/bef40531f0820b8ba1869524b3a9830a10413b1b/apps/files_sharing/openapi.json#L1524
this field is **required** and default is "-1"

and so on...

Created it here to not spam Nextcloud/server repository

**Comment by provokateurin** [comment]
Will be fixed with https://github.com/nextcloud/server/pull/39330.
