### ISSUE TITLE
Hardcoded path in iframe

### ISSUE THREAD

**Issue by coyoteseattle** [provokateurin/ocs_api_viewer#6]
If the nextcloud install is in a subdirectory on the webserver, such as https://serverexample.com/nextcloud/, this fails because templates/iframe.php refers to all of its assets by absolute path as /apps/ocs_api_viewer/<asset>, which don't exist.  
I corrected this on my install by modifying those URLs to instead be ../<asset>, but refrained from putting in a pull request, because I assume that there's a more correct way to do that which I'm not familiar with.

**Comment by provokateurin** [comment]
This bug has been reported by others as well. They had the app in a custom app directory, so the hardcoded path made it fail there too.
